{% set version = "1.0.1" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: jupyter_server_ydoc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter_server_ydoc/jupyter_server_ydoc-{{ version }}.tar.gz
  sha256: 6c9937f93fc7f18d43dcd4e82e5c8b71e4013e3953240ef2fbd73b3c337a28f7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python {{ python_min }}

  run:
    - jsonschema >=4.18.0
    - jupyter_events >=0.10.0
    - jupyter_server >=2.11.1,<3.0.0
    - jupyter_server_fileid >=0.7.0,<1
    - jupyter_ydoc >=2.1.2,<4.0.0
    - pycrdt
    - pycrdt-websocket >=0.15.0,<0.16.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyter_server_ydoc
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab/jupyter_collaboration
  license: BSD-3-Clause
  license_file: LICENSE
  summary: jupyter-server extension integrating collaborative shared models.

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
