{% set version = "1.0.0" %}

package:
  name: jupyter_server_ydoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_server_ydoc/jupyter_server_ydoc-{{ version }}.tar.gz
  sha256: 3017524c1da068815b748c8f1ebe7ec08eda047fc597ce72c125b18009a391e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - hatchling >=0.25
    - pip
    - python >=3.7

  run:
    - jupyter_server_fileid >=0.6.0,<1
    - jupyter_ydoc >=0.2.0,<0.4.0
    - python >=3.7
    - ypy-websocket >=0.8.2,<0.9.0

test:
  source_files:
    - tests
  requires:
    - jupyter_server >=2.0.0a0
    - pip
    - pytest >=7.0
    - pytest-cov
    - pytest-jupyter-server
    - pytest-timeout
    - pytest-tornasync
  imports:
    - jupyter_server_ydoc
  commands:
    - pip check
    - pytest -vv --no-cov-on-fail --cov-report=term-missing:skip-covered --cov=jupyter_server_ydoc --cov-fail-under=27

about:
  home: https://github.com/jupyterlab/jupyter_collaboration
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Server Extension providing support for Y documents.

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
