# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.4.2"
  python_check_max: "3.14"
  # mismatch-sensitve upstream deps
  jupyter_ydoc_min: "4.1.1"
  jupyter_server_min: "2.19.0"
  pycrdt_websocket_min: "0.16.4"
  # testing
  grep: ${{ "grep -iE" if unix else "findstr /c" }}
  cov_fail_under: "75"
  pytest_k: |-
    -k "not room_handler_doc_client_should_emit_awareness_event"

package:
  name: jupyter_server_ydoc
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/ae/14/88e5aaaf26ea19320269c4c12db748ed6d1912abd032365879d9e549fe2d/jupyter_server_ydoc-${{ version }}.tar.gz
  sha256: 8bb9d8cdf3441d6a5d25d6a66fe5b946c5acbc65c87e0df63c0d2f43ce92c47d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python ${{ python_min }}.*
  run:
    - jsonschema >=4.18.0
    - jupyter_events >=0.11.0
    - jupyter_server >=${{ jupyter_server_min }},<3.0.0
    - jupyter_server_fileid >=0.7.0,<1
    - jupyter_ydoc >=${{ jupyter_ydoc_min }},<4.0.0
    - pycrdt
    - pycrdt-websocket >=${{ pycrdt_websocket_min }},<0.17.0
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyter_server_ydoc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - jupyter_server ${{ jupyter_server_min }}.*
        - jupyter_ydoc ${{ jupyter_ydoc_min }}.*
        - pycrdt-websocket ${{ pycrdt_websocket_min }}.*
    script:
      - pip check
  - files:
      source:
        - tests/
    requirements:
      run:
        - dirty-equals
        - httpx-ws >=0.5.2
        - pytest-cov
        - python ${{ python_min }}.*
        - pytest-jupyter
        - pip
    script:
      env:
        JUPYTER_PLATFORM_DIRS: "1"
      content:
        - pip check
        - jupyter server extension list
        - jupyter server extension list 2>&1 | ${{ grep }} "jupyter_server_ydoc.*${{ version | replace(".", "\\.") }}.*OK"
        - coverage run --source=jupyter_server_ydoc --branch -m pytest -vv --tb=long --color=yes ${{ pytest_k }}
        - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: jupyter-server extension integrating collaborative shared models.
  homepage: https://pypi.org/project/jupyter-server-ydoc
  repository: https://github.com/jupyterlab/jupyter_collaboration

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
